### ISSUE TITLE
Configuring on another Host 

### ISSUE THREAD

**Issue by KeksTheAllmighty** [rylativity/opensearch-nginx-keycloak#2]
Hey, 

first of all thank you for a great solution out there :+1: 

Currently I am trying to deploy it on another host in my network and I am facing an issue:

After cert generation, once I run the `docker-compose up -d postgres keycloak nginx` all the containers seem to run nicely.
Then when I actually try to login, my browser is redircted to `http://localhost/auth/admin/` which ofcourse fails because I am running the infrastructure on the different machine.

I was trying to change the `command: ["-Dkeycloak.frontendUrl=http://localhost/auth"]` replacing the localhost with an ip...
Also tried to mess with the nginx config but that also didnt help....

It seems to be some config error to me.

So my question is, what is the correct way of setting up a different base IP if I am running the infrastructure on another host.

Thank you and have a nice day

**Comment by rylativity** [comment]
Hi @KeksTheAllmighty,

You are definitely looking in the right place.  I just ran a quick test and was able to get it working on a remote host just by changing the value "localhost" in the `command: ["-Dkeycloak.frontendUrl=http://localhost/auth"]` line to an IP address.  If you are just starting the postgres, keycloak, and nginx containers, it should not require any other changes to the nginx.conf or any of the other files. (Note: You will need to change the value of `opensearch_security.openid.base_redirect_url:` near the bottom of opensearch_dashboards.yml by replacing "localhost" with your remote IP address before starting opensearch and opensearch dashboards.)

If you want to test a "remote" connection without having to worry about other variables that may be causing issues, you can run it on your local laptop or desktop and attempt to connect to it from another device on your network.  For example, if you are on mac or linux, you can:
1.  run `ifconfig` in a terminal to find your laptop's local network IP address.  You'll see a decent amount of output, but there should be an IP address that starts with `192.168`, likely under the `en0:` section of the output.  This is your devices local IP.  (If you are on windows, I believe `ipconfig` will give you your local IP address)
2. Replace localhost in `command: ["-Dkeycloak.frontendUrl=http://localhost/auth"]` with that IP address.  For example, `command: ["-Dkeycloak.frontendUrl=http://192.168.1.212/auth"]` and run `docker-compose up -d --force-recreate postgres keycloak nginx`
3. Using another device (e.g. a smartphone or another laptop), open a web browser and go to 192.168.1.212/auth (but using whatever your device's IP address was from steps 1 and 2).  You should be able to login to the admin portal and all redirects should be to the correct IP address that you configured in the docker-compose.yml.

I just pushed a commit updating the README to include instructions for deploying to another IP address, and I also removed the keycloak container's healthcheck, which may have been preventing it from starting up.  Please do a `git pull` or fresh `git glone`, confirm any changes you made to nginx.conf (or other files) have been reverted, change "localhost" to your IP address in the `command: ["-Dkeycloak.frontendUrl=http://localhost/auth"]` line, and run `docker-compose up -d --force-recreate postgres keycloak nginx`.

Let me know if that works for you, or if you are still having problems.

**Comment by KeksTheAllmighty** [comment]
Hey @rylativity ,

thank you for your response. I think my error was that i didnt recreate the keycloak container. 

Let's say my external IP is `10.10.13.106`
So after following your instructions I am able to authenticate in keycloak, create a confidential `opensearch` client and set up the realm role mappers. Then I copied secret to the `config/opensearch_dashboards.yml`. Further I deleted the old opensearch+dashboard containers and rerun `docker-compose up -d --build opensearch-node1 opensearch-dashboards`.

So when I got to:
`10.10.13.106/kibana`
I am first redirected to keycloak login at:
`http://10.10.13.106/auth/realms/master/protocol/openid-connect/auth?client_id=opensearch&response_type=code&redirect_uri=http%3A%2F%2F10.10.13.106%2Fkibana%2Fauth%2Fopenid%2Flogin&state=mEYbiMUm2oZ9o6wG_NJi1w&scope=openid%20profile%20email%20address%20phone`

Here I input the keycloak admin credentials and boom, I seem to not be able to login to kibana.
![image](https://user-images.githubusercontent.com/68150167/151982134-e35ebfb5-355e-4143-97a9-55a4066dad8a.png)

This is funny because the whole scenario does work for me on localhost (using the same keycloak settings).
Another question: what docker-compose version do you use?

**Comment by rylativity** [comment]
@KeksTheAllmighty This probably means that the opensearch-dashboards cant authenticate the user, most likely because opensearch-dashboards can't connect to keycloak.  In my experience, opensearch-dashboards attempts to find keycloak _exactly once_ and if it fails to connect to keycloak, it won't work until you restart.  Try checking the log files of the opensearch-dashboards container for a log line that looks like this - https://github.com/rylativity/opensearch-nginx-keycloak/blob/2dae420ca28cba0bdcccdb881194d495102cc1a4/logs.txt#L1211  (you can just CTRL+F for ".well-known" in your logs and it will jump to that line if there was an error connecting).  If you don't see this line, then it was able to connect to the keycloak container successfully.

## If you do see opensearch-dashboards having an issue connecting to keycloak
Assuming you don't have any data stored in opensearch at this point, I have found that the easiest solution is to delete the opensearch/opensearch-dashboard containers AND the volume ("opensearch-data1" if you haven't changed the docker-compose.yml).  Can you try running:
1. `docker-compose stop opensearch-node1 opensearch-dashboards`
2. `docker rm -f opensearch-node1 opensearch-dashboards`
3. `docker volume rm opensearch-nginx-keycloak_opensearch-data1` (note: the part of the volume name before the "_opensearch-data1" depends on the directory you ran `docker-compose up` to start the containers, so that may be different for you)
4. Confirm that keycloak, nginx, and postgres are still running, and then run `docker-compose up -d --build opensearch-node1 opensearch-dashboards`

## If you don't see any issue with the opensearch-dashboards/keycloak connection
Another possibility - If you dont see an issue with the keycloak connection, check the log files to see if your users JWT token is being denied.  Opensearch may not be able to find the JWKS URI, in which case you can set it explicitly in the securityconfig.yml file. If that is the issue, add that line and run the same 4 steps detailed above to completely restart/refresh your opensearch containers. I've now committed that change as well (https://github.com/rylativity/opensearch-nginx-keycloak/blob/master/config/securityconfig.yml#L104), so you can see exactly what should be added. 

Hopefully that resolves the issue.  A couple other notes:
- You shouldn't need to make any changes to nginx.conf to get this to work (although obviously feel free to make whatever changes you and your team need for your use case)
- The value for `opensearch_security.openid.base_redirect_url:` in opensearch_dashboards.yml must match the url where you expect to access opensearch-dashboards on the remote machine from your local browser (with the example IP you gave, this should be set to 10.10.13.106/kibana; it looks like you have this set correctly based on the redirect url from your screenshot).  The URI ("/kibana") must also be set under the SERVER_BASEPATH key in the docker-compose.yml
- The value for `opensearch_security.openid.connect_url:` in opensearch_dashboards.yml should not change.  This is where the opensearch-dashboards container can find keycloak (not where a remote user can find keycloak), so we use the keycloak service name.

Please let me know if either of the suggestions above solve the issue.  If you are still having problems with the redirect, will you share your config files (redacting any sensitive values), and the log files from opensearch-dashboards and opensearch-node1?  You can get the log files by running `docker-compose logs -f opensearch-node1 opensearch-dashboards | tee logs.txt` this will output the logs and also write them to a file called "logs.txt".

**Comment by KeksTheAllmighty** [comment]
Hey again, hope you are having a nice day :)

I checked up the logs and there was no line with `.well-known` in it. 

So I tried using the jwksuri fix. But also faced the same problem (too many redirects). It also appears that the `config/securityconfig,yml` as well as the `config/opensearch.yml` are commented out in the `docker-compose.yml`. I tried commenting just these 2 back in, which resulted in same redirect error when logging in to opensearch. I also tried commenting everything in but there were some files missing.

I also  tried deploying in another network on different machines, and got stuck with the same issue with too many redirects (ERR_TOO_MANY_REDIRECTS). So the issue should be reproducible.

So here are the config files, they are basically the same as yours, just edited the base IP and the client secret. 

docker-compose.yml: (i left config/opensearch.yml commented out as it contained some SSL stuff which i didnt want to use anyway)
```
version: '3.9'
services:
  opensearch-node1:
    #<<: *opensearch-common
    # image: opensearchproject/opensearch:latest
    build: .
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      # - cluster.name=opensearch-cluster
      # - node.name=opensearch-node1
      # - discovery.seed_hosts=opensearch-node1,opensearch-node2
      # - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - DISABLE_INSTALL_DEMO_CONFIG=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
    container_name: opensearch-node1
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      # - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
      # - ./certs/node.pem:/usr/share/opensearch/config/node.pem
      # - ./certs/node-key.pem:/usr/share/opensearch/config/node-key.pem
      # - ./certs/admin.pem:/usr/share/opensearch/config/admin.pem
      # - ./certs/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
      # - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - ./config/securityconfig.yml:/usr/share/opensearch/securityconfig/config.yml
      # - ./config/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      # - ./config/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
      # - ./config/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml
      # - ./config/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
      # - ./config/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
  # opensearch-node2:
  #   # image: opensearchproject/opensearch:latest
  #   build: .
  #   container_name: opensearch-node2
  #   environment:
  #     - cluster.name=opensearch-cluster
  #     - node.name=opensearch-node2
  #     - discovery.seed_hosts=opensearch-node1,opensearch-node2
  #     - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
  #     - bootstrap.memory_lock=true
  #     - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - DISABLE_INSTALL_DEMO_CONFIG=true
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   volumes:
  #     - opensearch-data2:/usr/share/opensearch/data
  #     # - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem
  #     # - ./certs/node.pem:/usr/share/opensearch/config/node.pem
  #     # - ./certs/node-key.pem:/usr/share/opensearch/config/node-key.pem
  #     # - ./certs/admin.pem:/usr/share/opensearch/config/admin.pem
  #     # - ./certs/admin-key.pem:/usr/share/opensearch/config/admin-key.pem
  #     # - ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
  #     # - ./config/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
  #     # - ./config/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
  #     # - ./config/tenants.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/tenants.yml
  #     # - ./config/roles.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles.yml
  #     # - ./config/action_groups.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/action_groups.yml
  #   networks:
  #     - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    # ports:
    #   - 5601:5601
    # expose:
    #   - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
      SERVER_BASEPATH: /kibana
      SERVER_REWRITEBASEPATH: "true"
    volumes:
      - ./config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml
    networks:
      - opensearch-net
  nginx:
    build:
      context: ./nginx_conf/
    ports:
      - 80:80
    networks:
      - opensearch-net
  postgres:
    image: postgres:13
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    # healthcheck:
    #   test: ["CMD", "pg_isready"]
    restart: always
    networks:
      - opensearch-net
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["-Dkeycloak.frontendUrl=http://10.10.13.106/auth"]
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
#      KEYCLOAK_LOGLEVEL: DEBUG
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
    depends_on:
      - postgres
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  keycloak_postgres_data:

networks:
  opensearch-net:
```

securityconfig.yml
```
# This is the main Open Distro Security configuration file where authentication
# and authorization is defined.
#
# You need to configure at least one authentication domain in the authc of this file.
# An authentication domain is responsible for extracting the user credentials from
# the request and for validating them against an authentication backend like Active Directory for example.
#
# If more than one authentication domain is configured the first one which succeeds wins.
# If all authentication domains fail then the request is unauthenticated.
# In this case an exception is thrown and/or the HTTP status is set to 401.
#
# After authentication authorization (authz) will be applied. There can be zero or more authorizers which collect
# the roles from a given backend for the authenticated user.
#
# Both, authc and auth can be enabled/disabled separately for REST and TRANSPORT layer. Default is true for both.
#        http_enabled: true
#        transport_enabled: true
#
# For HTTP it is possible to allow anonymous authentication. If that is the case then the HTTP authenticators try to
# find user credentials in the HTTP request. If credentials are found then the user gets regularly authenticated.
# If none can be found the user will be authenticated as an "anonymous" user. This user has always the username "anonymous"
# and one role named "anonymous_backendrole".
# If you enable anonymous authentication all HTTP authenticators will not challenge.
#
#
# Note: If you define more than one HTTP authenticators make sure to put non-challenging authenticators like "proxy" or "clientcert"
# first and the challenging one last.
# Because it's not possible to challenge a client with two different authentication methods (for example
# Kerberos and Basic) only one can have the challenge flag set to true. You can cope with this situation
# by using pre-authentication, e.g. sending a HTTP Basic authentication header in the request.
#
# Default value of the challenge flag is true.
#
#
# HTTP
#   basic (challenging)
#   proxy (not challenging, needs xff)
#   kerberos (challenging)
#   clientcert (not challenging, needs https)
#   jwt (not challenging)
#   host (not challenging) #DEPRECATED, will be removed in a future version.
#                          host based authentication is configurable in roles_mapping

# Authc
#   internal
#   noop
#   ldap

# Authz
#   ldap
#   noop



_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    #filtered_alias_mode: warn
    #do_not_fail_on_forbidden: false
    # kibana:
    # # Kibana multitenancy
    #   multitenancy_enabled: true
    #   server_username: kibanaserver
    #   index: '.kibana'
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        #internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        internalProxies: '.*' # trust all internal proxies, regex pattern
        remoteIpHeader:  'x-forwarded-for'
        ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
        ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
        ###### and here https://tools.ietf.org/html/rfc7239
        ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: http://keycloak:8080/auth/realms/master/.well-known/openid-configuration
            jwks_uri: http://keycloak:8080/auth/realms/master/protocol/openid-connect/certs
            openid_connect_idp.enable_ssl: false
            openid_connect_idp.verify_hostnames: false
            skip_users:
              - kibanaro
              - kibanaserver
              - logstash
              - adminp
              - kibanauser
              - filebeat_internal
        authentication_backend:
          type: noop

      # proxy_auth_domain:
      #   http_enabled: true
      #   transport_enabled: true
      #   order: 0
      #   http_authenticator:
      #     type: proxy
      #     challenge: false
      #     config:
      #       user_header: "x-proxy-user"
      #       roles_header: "x-proxy-roles"
      #       skip_users:
      #         - "kibanaserver"
      #         - "kibana"
      #         - "apm_system"
      #         - "logstash_system"
      #         - "beats_system"
      #         - "remote_monitoring_user"
      #         - "elastic"
      #   authentication_backend:
      #     type: noop
```

opensearch_dashboards.yml
```
# OpenSearch Dashboards is served by a back end server. This setting specifies the port to use.
server.port: 5601

# Specifies the address to which the OpenSearch Dashboards server will bind. IP addresses and host names are both valid values.
# The default is 'localhost', which usually means remote machines will not be able to connect.
# To allow connections from remote users, set this parameter to a non-loopback address.
server.host: "0.0.0.0"

# Enables you to specify a path to mount OpenSearch Dashboards at if you are running behind a proxy.
# Use the `server.rewriteBasePath` setting to tell OpenSearch Dashboards if it should remove the basePath
# from requests it receives, and to prevent a deprecation warning at startup.
# This setting cannot end in a slash.
server.basePath: "/kibana"

# Specifies whether OpenSearch Dashboards should rewrite requests that are prefixed with
# `server.basePath` or require that they are rewritten by your reverse proxy.
server.rewriteBasePath: true

# The maximum payload size in bytes for incoming server requests.
#server.maxPayloadBytes: 1048576

# The OpenSearch Dashboards server's name.  This is used for display purposes.
#server.name: "your-hostname"

# The URLs of the OpenSearch instances to use for all your queries.
opensearch.hosts: ["https://opensearch-node1:9200"]

# OpenSearch Dashboards uses an index in OpenSearch to store saved searches, visualizations and
# dashboards. OpenSearch Dashboards creates a new index if the index doesn't already exist.
#opensearchDashboards.index: ".opensearch_dashboards"

# The default application to load.
opensearchDashboards.defaultAppId: "home"

# Setting for an optimized healthcheck that only uses the local OpenSearch node to do Dashboards healthcheck.
# This settings should be used for large clusters or for clusters with ingest heavy nodes.
# It allows Dashboards to only healthcheck using the local OpenSearch node rather than fan out requests across all nodes.
#
# It requires the user to create an OpenSearch node attribute with the same name as the value used in the setting
# This node attribute should assign all nodes of the same cluster an integer value that increments with each new cluster that is spun up
# e.g. in opensearch.yml file you would set the value to a setting using node.attr.cluster_id:
# Should only be enabled if there is a corresponding node attribute created in your OpenSearch config that matches the value here
#opensearch.optimizedHealthcheckId: "cluster_id"

# If your OpenSearch is protected with basic authentication, these settings provide
# the username and password that the OpenSearch Dashboards server uses to perform maintenance on the OpenSearch Dashboards
# index at startup. Your OpenSearch Dashboards users still need to authenticate with OpenSearch, which
# is proxied through the OpenSearch Dashboards server.
opensearch.username: "kibanaserver"
opensearch.password: "kibanaserver"

# Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
# These settings enable SSL for outgoing requests from the OpenSearch Dashboards server to the browser.
server.ssl.enabled: false
#server.ssl.certificate: /path/to/your/server.crt
#server.ssl.key: /path/to/your/server.key

# Optional settings that provide the paths to the PEM-format SSL certificate and key files.
# These files are used to verify the identity of OpenSearch Dashboards to OpenSearch and are required when
# xpack.security.http.ssl.client_authentication in OpenSearch is set to required.
#opensearch.ssl.certificate: /path/to/your/client.crt
#opensearch.ssl.key: /path/to/your/client.key

# Optional setting that enables you to specify a path to the PEM file for the certificate
# authority for your OpenSearch instance.
#opensearch.ssl.certificateAuthorities: [ "/path/to/your/CA.pem" ]

# To disregard the validity of SSL certificates, change this setting's value to 'none'.
opensearch.ssl.verificationMode: none

# Time in milliseconds to wait for OpenSearch to respond to pings. Defaults to the value of
# the opensearch.requestTimeout setting.
#opensearch.pingTimeout: 1500

# Time in milliseconds to wait for responses from the back end or OpenSearch. This value
# must be a positive integer.
#opensearch.requestTimeout: 30000

# List of OpenSearch Dashboards client-side headers to send to OpenSearch. To send *no* client-side
# headers, set this value to [] (an empty list).
opensearch.requestHeadersWhitelist: [ "Authorization", "securitytenant", "x-forwarded-for","x-proxy-user","x-proxy-roles"]

# Header names and values that are sent to OpenSearch. Any custom headers cannot be overwritten
# by client-side headers, regardless of the opensearch.requestHeadersWhitelist configuration.
#opensearch.customHeaders: {}

# Time in milliseconds for OpenSearch to wait for responses from shards. Set to 0 to disable.
#opensearch.shardTimeout: 30000

# Logs queries sent to OpenSearch. Requires logging.verbose set to true.
#opensearch.logQueries: false

# Specifies the path where OpenSearch Dashboards creates the process ID file.
#pid.file: /var/run/opensearchDashboards.pid

# Enables you to specify a file where OpenSearch Dashboards stores log output.
#logging.dest: stdout

# Set the value of this setting to true to suppress all logging output.
#logging.silent: false

# Set the value of this setting to true to suppress all logging output other than error messages.
logging.quiet: false

# Set the value of this setting to true to log all events, including system usage information
# and all requests.
logging.verbose: true

# Set the interval in milliseconds to sample system and process performance
# metrics. Minimum is 100ms. Defaults to 5000.
#ops.interval: 5000

# Specifies locale to be used for all localizable strings, dates and number formats.
# Supported languages are the following: English - en , by default , Chinese - zh-CN .
#i18n.locale: "en"

# Set the allowlist to check input graphite Url. Allowlist is the default check list.
#vis_type_timeline.graphiteAllowedUrls: ['https://www.hostedgraphite.com/UID/ACCESS_KEY/graphite']

# Set the blocklist to check input graphite Url. Blocklist is an IP list.
# Below is an example for reference
# vis_type_timeline.graphiteBlockedIPs: [
#  //Loopback
#  '127.0.0.0/8',
#  '::1/128',
#  //Link-local Address for IPv6
#  'fe80::/10',
#  //Private IP address for IPv4
#  '10.0.0.0/8',
#  '172.16.0.0/12',
#  '192.168.0.0/16',
#  //Unique local address (ULA)
#  'fc00::/7',
#  //Reserved IP address
#  '0.0.0.0/8',
#  '100.64.0.0/10',
#  '192.0.0.0/24',
#  '192.0.2.0/24',
#  '198.18.0.0/15',
#  '192.88.99.0/24',
#  '198.51.100.0/24',
#  '203.0.113.0/24',
#  '224.0.0.0/4',
#  '240.0.0.0/4',
#  '255.255.255.255/32',
#  '::/128',
#  '2001:db8::/32',
#  'ff00::/8',
# ]
#vis_type_timeline.graphiteBlockedIPs: []

# opensearchDashboards.branding:
  # logo:
    # defaultUrl: ""
    # darkModeUrl: ""
  # mark:
    # defaultUrl: ""
    # darkModeUrl: ""
  # loadingLogo:
    # defaultUrl: ""
    # darkModeUrl: ""
  # faviconUrl: ""
  # applicationTitle: ""

# Set the value of this setting to true to capture region blocked warnings and errors
# for your map rendering services.
# map.showRegionBlockedWarning: false

opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Private", "Global"]
opensearch_security.multitenancy.tenants.enable_global: true
opensearch_security.multitenancy.tenants.enable_private: true
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
opensearch_security.cookie.secure: true
opensearch_security.auth.type: "openid"
opensearch_security.openid.connect_url: "http://keycloak:8080/auth/realms/master/.well-known/openid-configuration"
opensearch_security.openid.client_id: "opensearch"
opensearch_security.openid.client_secret: "irNiktVxKG1tdPgfreuqW2MTvC7nU5cf"
opensearch_security.openid.base_redirect_url: "http://10.10.13.106/kibana"
opensearch_security.openid.verify_hostnames: false
server.xsrf.whitelist: ["/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
```

And here is the log:
[log.txt](https://github.com/rylativity/opensearch-nginx-keycloak/files/7982680/log.txt)

It seems to me that some cookie is not being set resulting in unauthorized error and a redirect. As far as I understand the 302 status is okay.
